//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_ApuestaPartido_Partido", "Partido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.Partido), "ApuestaPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.ApuestaPartido), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_ApuestaPartido_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.Usuario), "ApuestaPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.ApuestaPartido), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_Equipo_Grupo", "Grupo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.Grupo), "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.Equipo), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_EquipoPartido_Equipo", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.Equipo), "EquipoPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.EquipoPartido), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_EquipoPartido_Partido", "Partido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.Partido), "EquipoPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.EquipoPartido), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "FK_Partido_FasePartido", "FasePartido", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApuestasPolla.Models.FasePartido), "Partido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.Partido), true)]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "PuntajeApuesta", "ApuestaPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.ApuestaPartido), "TipoPuntaje", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.TipoPuntaje))]
[assembly: EdmRelationshipAttribute("MVCpruebasModel", "PuntajePartido", "EquipoPartido", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.EquipoPartido), "TipoPuntaje", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApuestasPolla.Models.TipoPuntaje))]

#endregion

namespace ApuestasPolla.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PollaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PollaEntities object using the connection string found in the 'PollaEntities' section of the application configuration file.
        /// </summary>
        public PollaEntities() : base("name=PollaEntities", "PollaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PollaEntities object.
        /// </summary>
        public PollaEntities(string connectionString) : base(connectionString, "PollaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PollaEntities object.
        /// </summary>
        public PollaEntities(EntityConnection connection) : base(connection, "PollaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ApuestaPartido> ApuestaPartido
        {
            get
            {
                if ((_ApuestaPartido == null))
                {
                    _ApuestaPartido = base.CreateObjectSet<ApuestaPartido>("ApuestaPartido");
                }
                return _ApuestaPartido;
            }
        }
        private ObjectSet<ApuestaPartido> _ApuestaPartido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Equipo> Equipo
        {
            get
            {
                if ((_Equipo == null))
                {
                    _Equipo = base.CreateObjectSet<Equipo>("Equipo");
                }
                return _Equipo;
            }
        }
        private ObjectSet<Equipo> _Equipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EquipoPartido> EquipoPartido
        {
            get
            {
                if ((_EquipoPartido == null))
                {
                    _EquipoPartido = base.CreateObjectSet<EquipoPartido>("EquipoPartido");
                }
                return _EquipoPartido;
            }
        }
        private ObjectSet<EquipoPartido> _EquipoPartido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FasePartido> FasePartido
        {
            get
            {
                if ((_FasePartido == null))
                {
                    _FasePartido = base.CreateObjectSet<FasePartido>("FasePartido");
                }
                return _FasePartido;
            }
        }
        private ObjectSet<FasePartido> _FasePartido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Grupo> Grupo
        {
            get
            {
                if ((_Grupo == null))
                {
                    _Grupo = base.CreateObjectSet<Grupo>("Grupo");
                }
                return _Grupo;
            }
        }
        private ObjectSet<Grupo> _Grupo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Partido> Partido
        {
            get
            {
                if ((_Partido == null))
                {
                    _Partido = base.CreateObjectSet<Partido>("Partido");
                }
                return _Partido;
            }
        }
        private ObjectSet<Partido> _Partido;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoPuntaje> TipoPuntaje
        {
            get
            {
                if ((_TipoPuntaje == null))
                {
                    _TipoPuntaje = base.CreateObjectSet<TipoPuntaje>("TipoPuntaje");
                }
                return _TipoPuntaje;
            }
        }
        private ObjectSet<TipoPuntaje> _TipoPuntaje;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ApuestaPartido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToApuestaPartido(ApuestaPartido apuestaPartido)
        {
            base.AddObject("ApuestaPartido", apuestaPartido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Equipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipo(Equipo equipo)
        {
            base.AddObject("Equipo", equipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EquipoPartido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipoPartido(EquipoPartido equipoPartido)
        {
            base.AddObject("EquipoPartido", equipoPartido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FasePartido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFasePartido(FasePartido fasePartido)
        {
            base.AddObject("FasePartido", fasePartido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Grupo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGrupo(Grupo grupo)
        {
            base.AddObject("Grupo", grupo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Partido EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPartido(Partido partido)
        {
            base.AddObject("Partido", partido);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoPuntaje EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoPuntaje(TipoPuntaje tipoPuntaje)
        {
            base.AddObject("TipoPuntaje", tipoPuntaje);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="ApuestaPartido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ApuestaPartido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ApuestaPartido object.
        /// </summary>
        /// <param name="idApuestaPartido">Initial value of the IdApuestaPartido property.</param>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="idPartido">Initial value of the IdPartido property.</param>
        /// <param name="puntaje">Initial value of the Puntaje property.</param>
        /// <param name="marcadorLocal">Initial value of the MarcadorLocal property.</param>
        /// <param name="marcadorVisitante">Initial value of the MarcadorVisitante property.</param>
        public static ApuestaPartido CreateApuestaPartido(global::System.Int32 idApuestaPartido, global::System.Int32 idUsuario, global::System.Int32 idPartido, global::System.Int32 puntaje, global::System.Int32 marcadorLocal, global::System.Int32 marcadorVisitante)
        {
            ApuestaPartido apuestaPartido = new ApuestaPartido();
            apuestaPartido.IdApuestaPartido = idApuestaPartido;
            apuestaPartido.IdUsuario = idUsuario;
            apuestaPartido.IdPartido = idPartido;
            apuestaPartido.Puntaje = puntaje;
            apuestaPartido.MarcadorLocal = marcadorLocal;
            apuestaPartido.MarcadorVisitante = marcadorVisitante;
            return apuestaPartido;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdApuestaPartido
        {
            get
            {
                return _IdApuestaPartido;
            }
            set
            {
                if (_IdApuestaPartido != value)
                {
                    OnIdApuestaPartidoChanging(value);
                    ReportPropertyChanging("IdApuestaPartido");
                    _IdApuestaPartido = StructuralObject.SetValidValue(value, "IdApuestaPartido");
                    ReportPropertyChanged("IdApuestaPartido");
                    OnIdApuestaPartidoChanged();
                }
            }
        }
        private global::System.Int32 _IdApuestaPartido;
        partial void OnIdApuestaPartidoChanging(global::System.Int32 value);
        partial void OnIdApuestaPartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                OnIdUsuarioChanging(value);
                ReportPropertyChanging("IdUsuario");
                _IdUsuario = StructuralObject.SetValidValue(value, "IdUsuario");
                ReportPropertyChanged("IdUsuario");
                OnIdUsuarioChanged();
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPartido
        {
            get
            {
                return _IdPartido;
            }
            set
            {
                OnIdPartidoChanging(value);
                ReportPropertyChanging("IdPartido");
                _IdPartido = StructuralObject.SetValidValue(value, "IdPartido");
                ReportPropertyChanged("IdPartido");
                OnIdPartidoChanged();
            }
        }
        private global::System.Int32 _IdPartido;
        partial void OnIdPartidoChanging(global::System.Int32 value);
        partial void OnIdPartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puntaje
        {
            get
            {
                return _Puntaje;
            }
            set
            {
                OnPuntajeChanging(value);
                ReportPropertyChanging("Puntaje");
                _Puntaje = StructuralObject.SetValidValue(value, "Puntaje");
                ReportPropertyChanged("Puntaje");
                OnPuntajeChanged();
            }
        }
        private global::System.Int32 _Puntaje;
        partial void OnPuntajeChanging(global::System.Int32 value);
        partial void OnPuntajeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarcadorLocal
        {
            get
            {
                return _MarcadorLocal;
            }
            set
            {
                OnMarcadorLocalChanging(value);
                ReportPropertyChanging("MarcadorLocal");
                _MarcadorLocal = StructuralObject.SetValidValue(value, "MarcadorLocal");
                ReportPropertyChanged("MarcadorLocal");
                OnMarcadorLocalChanged();
            }
        }
        private global::System.Int32 _MarcadorLocal;
        partial void OnMarcadorLocalChanging(global::System.Int32 value);
        partial void OnMarcadorLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MarcadorVisitante
        {
            get
            {
                return _MarcadorVisitante;
            }
            set
            {
                OnMarcadorVisitanteChanging(value);
                ReportPropertyChanging("MarcadorVisitante");
                _MarcadorVisitante = StructuralObject.SetValidValue(value, "MarcadorVisitante");
                ReportPropertyChanged("MarcadorVisitante");
                OnMarcadorVisitanteChanged();
            }
        }
        private global::System.Int32 _MarcadorVisitante;
        partial void OnMarcadorVisitanteChanging(global::System.Int32 value);
        partial void OnMarcadorVisitanteChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_ApuestaPartido_Partido", "Partido")]
        public Partido Partido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "Partido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "Partido").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partido> PartidoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "Partido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "Partido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_ApuestaPartido_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "Usuario", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "PuntajeApuesta", "TipoPuntaje")]
        public EntityCollection<TipoPuntaje> TipoPuntaje
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TipoPuntaje>("MVCpruebasModel.PuntajeApuesta", "TipoPuntaje");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TipoPuntaje>("MVCpruebasModel.PuntajeApuesta", "TipoPuntaje", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="Equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Equipo object.
        /// </summary>
        /// <param name="idEquipo">Initial value of the IdEquipo property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="idGrupo">Initial value of the IdGrupo property.</param>
        public static Equipo CreateEquipo(global::System.Int32 idEquipo, global::System.String nombre, global::System.Int32 idGrupo)
        {
            Equipo equipo = new Equipo();
            equipo.IdEquipo = idEquipo;
            equipo.Nombre = nombre;
            equipo.IdGrupo = idGrupo;
            return equipo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipo
        {
            get
            {
                return _IdEquipo;
            }
            set
            {
                if (_IdEquipo != value)
                {
                    OnIdEquipoChanging(value);
                    ReportPropertyChanging("IdEquipo");
                    _IdEquipo = StructuralObject.SetValidValue(value, "IdEquipo");
                    ReportPropertyChanged("IdEquipo");
                    OnIdEquipoChanged();
                }
            }
        }
        private global::System.Int32 _IdEquipo;
        partial void OnIdEquipoChanging(global::System.Int32 value);
        partial void OnIdEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RutaImagen
        {
            get
            {
                return _RutaImagen;
            }
            set
            {
                OnRutaImagenChanging(value);
                ReportPropertyChanging("RutaImagen");
                _RutaImagen = StructuralObject.SetValidValue(value, true, "RutaImagen");
                ReportPropertyChanged("RutaImagen");
                OnRutaImagenChanged();
            }
        }
        private global::System.String _RutaImagen;
        partial void OnRutaImagenChanging(global::System.String value);
        partial void OnRutaImagenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGrupo
        {
            get
            {
                return _IdGrupo;
            }
            set
            {
                OnIdGrupoChanging(value);
                ReportPropertyChanging("IdGrupo");
                _IdGrupo = StructuralObject.SetValidValue(value, "IdGrupo");
                ReportPropertyChanged("IdGrupo");
                OnIdGrupoChanged();
            }
        }
        private global::System.Int32 _IdGrupo;
        partial void OnIdGrupoChanging(global::System.Int32 value);
        partial void OnIdGrupoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_Equipo_Grupo", "Grupo")]
        public Grupo Grupo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("MVCpruebasModel.FK_Equipo_Grupo", "Grupo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("MVCpruebasModel.FK_Equipo_Grupo", "Grupo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Grupo> GrupoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Grupo>("MVCpruebasModel.FK_Equipo_Grupo", "Grupo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Grupo>("MVCpruebasModel.FK_Equipo_Grupo", "Grupo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_EquipoPartido_Equipo", "EquipoPartido")]
        public EntityCollection<EquipoPartido> EquipoPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EquipoPartido>("MVCpruebasModel.FK_EquipoPartido_Equipo", "EquipoPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EquipoPartido>("MVCpruebasModel.FK_EquipoPartido_Equipo", "EquipoPartido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="EquipoPartido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EquipoPartido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EquipoPartido object.
        /// </summary>
        /// <param name="idEquipoPartido">Initial value of the IdEquipoPartido property.</param>
        /// <param name="idEquipo">Initial value of the IdEquipo property.</param>
        /// <param name="idPartido">Initial value of the IdPartido property.</param>
        /// <param name="puntos">Initial value of the Puntos property.</param>
        /// <param name="goles">Initial value of the Goles property.</param>
        /// <param name="golesContra">Initial value of the GolesContra property.</param>
        /// <param name="ubicacion">Initial value of the Ubicacion property.</param>
        public static EquipoPartido CreateEquipoPartido(global::System.Int32 idEquipoPartido, global::System.Int32 idEquipo, global::System.Int32 idPartido, global::System.Int32 puntos, global::System.Int32 goles, global::System.Int32 golesContra, global::System.String ubicacion)
        {
            EquipoPartido equipoPartido = new EquipoPartido();
            equipoPartido.IdEquipoPartido = idEquipoPartido;
            equipoPartido.IdEquipo = idEquipo;
            equipoPartido.IdPartido = idPartido;
            equipoPartido.Puntos = puntos;
            equipoPartido.Goles = goles;
            equipoPartido.GolesContra = golesContra;
            equipoPartido.Ubicacion = ubicacion;
            return equipoPartido;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipoPartido
        {
            get
            {
                return _IdEquipoPartido;
            }
            set
            {
                if (_IdEquipoPartido != value)
                {
                    OnIdEquipoPartidoChanging(value);
                    ReportPropertyChanging("IdEquipoPartido");
                    _IdEquipoPartido = StructuralObject.SetValidValue(value, "IdEquipoPartido");
                    ReportPropertyChanged("IdEquipoPartido");
                    OnIdEquipoPartidoChanged();
                }
            }
        }
        private global::System.Int32 _IdEquipoPartido;
        partial void OnIdEquipoPartidoChanging(global::System.Int32 value);
        partial void OnIdEquipoPartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipo
        {
            get
            {
                return _IdEquipo;
            }
            set
            {
                OnIdEquipoChanging(value);
                ReportPropertyChanging("IdEquipo");
                _IdEquipo = StructuralObject.SetValidValue(value, "IdEquipo");
                ReportPropertyChanged("IdEquipo");
                OnIdEquipoChanged();
            }
        }
        private global::System.Int32 _IdEquipo;
        partial void OnIdEquipoChanging(global::System.Int32 value);
        partial void OnIdEquipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPartido
        {
            get
            {
                return _IdPartido;
            }
            set
            {
                OnIdPartidoChanging(value);
                ReportPropertyChanging("IdPartido");
                _IdPartido = StructuralObject.SetValidValue(value, "IdPartido");
                ReportPropertyChanged("IdPartido");
                OnIdPartidoChanged();
            }
        }
        private global::System.Int32 _IdPartido;
        partial void OnIdPartidoChanging(global::System.Int32 value);
        partial void OnIdPartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puntos
        {
            get
            {
                return _Puntos;
            }
            set
            {
                OnPuntosChanging(value);
                ReportPropertyChanging("Puntos");
                _Puntos = StructuralObject.SetValidValue(value, "Puntos");
                ReportPropertyChanged("Puntos");
                OnPuntosChanged();
            }
        }
        private global::System.Int32 _Puntos;
        partial void OnPuntosChanging(global::System.Int32 value);
        partial void OnPuntosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Goles
        {
            get
            {
                return _Goles;
            }
            set
            {
                OnGolesChanging(value);
                ReportPropertyChanging("Goles");
                _Goles = StructuralObject.SetValidValue(value, "Goles");
                ReportPropertyChanged("Goles");
                OnGolesChanged();
            }
        }
        private global::System.Int32 _Goles;
        partial void OnGolesChanging(global::System.Int32 value);
        partial void OnGolesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GolesContra
        {
            get
            {
                return _GolesContra;
            }
            set
            {
                OnGolesContraChanging(value);
                ReportPropertyChanging("GolesContra");
                _GolesContra = StructuralObject.SetValidValue(value, "GolesContra");
                ReportPropertyChanged("GolesContra");
                OnGolesContraChanged();
            }
        }
        private global::System.Int32 _GolesContra;
        partial void OnGolesContraChanging(global::System.Int32 value);
        partial void OnGolesContraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ubicacion
        {
            get
            {
                return _Ubicacion;
            }
            set
            {
                OnUbicacionChanging(value);
                ReportPropertyChanging("Ubicacion");
                _Ubicacion = StructuralObject.SetValidValue(value, false, "Ubicacion");
                ReportPropertyChanged("Ubicacion");
                OnUbicacionChanged();
            }
        }
        private global::System.String _Ubicacion;
        partial void OnUbicacionChanging(global::System.String value);
        partial void OnUbicacionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_EquipoPartido_Equipo", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("MVCpruebasModel.FK_EquipoPartido_Equipo", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("MVCpruebasModel.FK_EquipoPartido_Equipo", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("MVCpruebasModel.FK_EquipoPartido_Equipo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("MVCpruebasModel.FK_EquipoPartido_Equipo", "Equipo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_EquipoPartido_Partido", "Partido")]
        public Partido Partido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_EquipoPartido_Partido", "Partido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_EquipoPartido_Partido", "Partido").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Partido> PartidoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Partido>("MVCpruebasModel.FK_EquipoPartido_Partido", "Partido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Partido>("MVCpruebasModel.FK_EquipoPartido_Partido", "Partido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "PuntajePartido", "TipoPuntaje")]
        public EntityCollection<TipoPuntaje> TipoPuntaje
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TipoPuntaje>("MVCpruebasModel.PuntajePartido", "TipoPuntaje");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TipoPuntaje>("MVCpruebasModel.PuntajePartido", "TipoPuntaje", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="FasePartido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FasePartido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FasePartido object.
        /// </summary>
        /// <param name="idFasePartido">Initial value of the IdFasePartido property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static FasePartido CreateFasePartido(global::System.Int32 idFasePartido, global::System.String descripcion)
        {
            FasePartido fasePartido = new FasePartido();
            fasePartido.IdFasePartido = idFasePartido;
            fasePartido.Descripcion = descripcion;
            return fasePartido;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFasePartido
        {
            get
            {
                return _IdFasePartido;
            }
            set
            {
                if (_IdFasePartido != value)
                {
                    OnIdFasePartidoChanging(value);
                    ReportPropertyChanging("IdFasePartido");
                    _IdFasePartido = StructuralObject.SetValidValue(value, "IdFasePartido");
                    ReportPropertyChanged("IdFasePartido");
                    OnIdFasePartidoChanged();
                }
            }
        }
        private global::System.Int32 _IdFasePartido;
        partial void OnIdFasePartidoChanging(global::System.Int32 value);
        partial void OnIdFasePartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_Partido_FasePartido", "Partido")]
        public EntityCollection<Partido> Partido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Partido>("MVCpruebasModel.FK_Partido_FasePartido", "Partido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Partido>("MVCpruebasModel.FK_Partido_FasePartido", "Partido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="Grupo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Grupo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Grupo object.
        /// </summary>
        /// <param name="idGrupo">Initial value of the IdGrupo property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Grupo CreateGrupo(global::System.Int32 idGrupo, global::System.String descripcion)
        {
            Grupo grupo = new Grupo();
            grupo.IdGrupo = idGrupo;
            grupo.Descripcion = descripcion;
            return grupo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdGrupo
        {
            get
            {
                return _IdGrupo;
            }
            set
            {
                if (_IdGrupo != value)
                {
                    OnIdGrupoChanging(value);
                    ReportPropertyChanging("IdGrupo");
                    _IdGrupo = StructuralObject.SetValidValue(value, "IdGrupo");
                    ReportPropertyChanged("IdGrupo");
                    OnIdGrupoChanged();
                }
            }
        }
        private global::System.Int32 _IdGrupo;
        partial void OnIdGrupoChanging(global::System.Int32 value);
        partial void OnIdGrupoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_Equipo_Grupo", "Equipo")]
        public EntityCollection<Equipo> Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Equipo>("MVCpruebasModel.FK_Equipo_Grupo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Equipo>("MVCpruebasModel.FK_Equipo_Grupo", "Equipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="Partido")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Partido : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Partido object.
        /// </summary>
        /// <param name="idPartido">Initial value of the IdPartido property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        /// <param name="idFase">Initial value of the IdFase property.</param>
        public static Partido CreatePartido(global::System.Int32 idPartido, global::System.DateTime fecha, global::System.Int32 idFase)
        {
            Partido partido = new Partido();
            partido.IdPartido = idPartido;
            partido.Fecha = fecha;
            partido.IdFase = idFase;
            return partido;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPartido
        {
            get
            {
                return _IdPartido;
            }
            set
            {
                if (_IdPartido != value)
                {
                    OnIdPartidoChanging(value);
                    ReportPropertyChanging("IdPartido");
                    _IdPartido = StructuralObject.SetValidValue(value, "IdPartido");
                    ReportPropertyChanged("IdPartido");
                    OnIdPartidoChanged();
                }
            }
        }
        private global::System.Int32 _IdPartido;
        partial void OnIdPartidoChanging(global::System.Int32 value);
        partial void OnIdPartidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdFase
        {
            get
            {
                return _IdFase;
            }
            set
            {
                OnIdFaseChanging(value);
                ReportPropertyChanging("IdFase");
                _IdFase = StructuralObject.SetValidValue(value, "IdFase");
                ReportPropertyChanged("IdFase");
                OnIdFaseChanged();
            }
        }
        private global::System.Int32 _IdFase;
        partial void OnIdFaseChanging(global::System.Int32 value);
        partial void OnIdFaseChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_ApuestaPartido_Partido", "ApuestaPartido")]
        public EntityCollection<ApuestaPartido> ApuestaPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApuestaPartido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "ApuestaPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApuestaPartido>("MVCpruebasModel.FK_ApuestaPartido_Partido", "ApuestaPartido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_EquipoPartido_Partido", "EquipoPartido")]
        public EntityCollection<EquipoPartido> EquipoPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EquipoPartido>("MVCpruebasModel.FK_EquipoPartido_Partido", "EquipoPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EquipoPartido>("MVCpruebasModel.FK_EquipoPartido_Partido", "EquipoPartido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_Partido_FasePartido", "FasePartido")]
        public FasePartido FasePartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FasePartido>("MVCpruebasModel.FK_Partido_FasePartido", "FasePartido").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FasePartido>("MVCpruebasModel.FK_Partido_FasePartido", "FasePartido").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FasePartido> FasePartidoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FasePartido>("MVCpruebasModel.FK_Partido_FasePartido", "FasePartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FasePartido>("MVCpruebasModel.FK_Partido_FasePartido", "FasePartido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false, "name");
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value, "principal_id");
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value, "diagram_id");
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value, "version");
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true, "definition");
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="TipoPuntaje")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoPuntaje : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoPuntaje object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="puntos">Initial value of the Puntos property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static TipoPuntaje CreateTipoPuntaje(global::System.Int32 id, global::System.String descripcion, global::System.Int32 puntos, global::System.String tipo)
        {
            TipoPuntaje tipoPuntaje = new TipoPuntaje();
            tipoPuntaje.Id = id;
            tipoPuntaje.Descripcion = descripcion;
            tipoPuntaje.Puntos = puntos;
            tipoPuntaje.Tipo = tipo;
            return tipoPuntaje;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false, "Descripcion");
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Puntos
        {
            get
            {
                return _Puntos;
            }
            set
            {
                OnPuntosChanging(value);
                ReportPropertyChanging("Puntos");
                _Puntos = StructuralObject.SetValidValue(value, "Puntos");
                ReportPropertyChanged("Puntos");
                OnPuntosChanged();
            }
        }
        private global::System.Int32 _Puntos;
        partial void OnPuntosChanging(global::System.Int32 value);
        partial void OnPuntosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false, "Tipo");
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "PuntajeApuesta", "ApuestaPartido")]
        public EntityCollection<ApuestaPartido> ApuestaPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApuestaPartido>("MVCpruebasModel.PuntajeApuesta", "ApuestaPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApuestaPartido>("MVCpruebasModel.PuntajeApuesta", "ApuestaPartido", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "PuntajePartido", "EquipoPartido")]
        public EntityCollection<EquipoPartido> EquipoPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EquipoPartido>("MVCpruebasModel.PuntajePartido", "EquipoPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EquipoPartido>("MVCpruebasModel.PuntajePartido", "EquipoPartido", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MVCpruebasModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="usuario1">Initial value of the Usuario1 property.</param>
        /// <param name="contrasena">Initial value of the Contrasena property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="modulo">Initial value of the Modulo property.</param>
        /// <param name="cedula">Initial value of the Cedula property.</param>
        public static Usuario CreateUsuario(global::System.Int32 idUsuario, global::System.String usuario1, global::System.String contrasena, global::System.String nombre, global::System.String apellido, global::System.String sexo, global::System.String modulo, global::System.Int32 cedula)
        {
            Usuario usuario = new Usuario();
            usuario.IdUsuario = idUsuario;
            usuario.Usuario1 = usuario1;
            usuario.Contrasena = contrasena;
            usuario.Nombre = nombre;
            usuario.Apellido = apellido;
            usuario.Sexo = sexo;
            usuario.Modulo = modulo;
            usuario.Cedula = cedula;
            return usuario;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value, "IdUsuario");
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario1
        {
            get
            {
                return _Usuario1;
            }
            set
            {
                OnUsuario1Changing(value);
                ReportPropertyChanging("Usuario1");
                _Usuario1 = StructuralObject.SetValidValue(value, false, "Usuario1");
                ReportPropertyChanged("Usuario1");
                OnUsuario1Changed();
            }
        }
        private global::System.String _Usuario1;
        partial void OnUsuario1Changing(global::System.String value);
        partial void OnUsuario1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contrasena
        {
            get
            {
                return _Contrasena;
            }
            set
            {
                OnContrasenaChanging(value);
                ReportPropertyChanging("Contrasena");
                _Contrasena = StructuralObject.SetValidValue(value, false, "Contrasena");
                ReportPropertyChanged("Contrasena");
                OnContrasenaChanged();
            }
        }
        private global::System.String _Contrasena;
        partial void OnContrasenaChanging(global::System.String value);
        partial void OnContrasenaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false, "Apellido");
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value, false, "Sexo");
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.String _Sexo;
        partial void OnSexoChanging(global::System.String value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Modulo
        {
            get
            {
                return _Modulo;
            }
            set
            {
                OnModuloChanging(value);
                ReportPropertyChanging("Modulo");
                _Modulo = StructuralObject.SetValidValue(value, false, "Modulo");
                ReportPropertyChanged("Modulo");
                OnModuloChanged();
            }
        }
        private global::System.String _Modulo;
        partial void OnModuloChanging(global::System.String value);
        partial void OnModuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Cedula
        {
            get
            {
                return _Cedula;
            }
            set
            {
                OnCedulaChanging(value);
                ReportPropertyChanging("Cedula");
                _Cedula = StructuralObject.SetValidValue(value, "Cedula");
                ReportPropertyChanged("Cedula");
                OnCedulaChanged();
            }
        }
        private global::System.Int32 _Cedula;
        partial void OnCedulaChanging(global::System.Int32 value);
        partial void OnCedulaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MVCpruebasModel", "FK_ApuestaPartido_Usuario", "ApuestaPartido")]
        public EntityCollection<ApuestaPartido> ApuestaPartido
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ApuestaPartido>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "ApuestaPartido");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ApuestaPartido>("MVCpruebasModel.FK_ApuestaPartido_Usuario", "ApuestaPartido", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
