//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApuestasPolla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPuntaje
    {
        public TipoPuntaje()
        {
            this.ApuestaPartido = new HashSet<ApuestaPartido>();
            this.EquipoPartido = new HashSet<EquipoPartido>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public int Puntos { get; set; }
        public string Tipo { get; set; }

        public virtual ICollection<ApuestaPartido> ApuestaPartido { get; set; }
        public virtual ICollection<EquipoPartido> EquipoPartido { get; set; }
    }
}
