//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApuestasPolla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApuestaPartido
    {
        public ApuestaPartido()
        {
            this.TipoPuntaje = new HashSet<TipoPuntaje>();
        }
    
        public int IdApuestaPartido { get; set; }
        public int IdUsuario { get; set; }
        public int IdPartido { get; set; }
        public int Puntaje { get; set; }
        public int MarcadorLocal { get; set; }
        public int MarcadorVisitante { get; set; }
    
        public virtual Partido Partido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<TipoPuntaje> TipoPuntaje { get; set; }
    }
}
