//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApuestasPolla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoPartido
    {
        public EquipoPartido()
        {
            this.TipoPuntaje = new HashSet<TipoPuntaje>();
        }
    
        public int IdEquipoPartido { get; set; }
        public int IdEquipo { get; set; }
        public int IdPartido { get; set; }
        public int Puntos { get; set; }
        public int Goles { get; set; }
        public int GolesContra { get; set; }
        public string Ubicacion { get; set; }
    
        public virtual Equipo Equipo { get; set; }
        public virtual Partido Partido { get; set; }
        public virtual ICollection<TipoPuntaje> TipoPuntaje { get; set; }
    }
}
