//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApuestasPolla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        public Grupo()
        {
            this.Equipo = new HashSet<Equipo>();
        }
    
        public int IdGrupo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Equipo> Equipo { get; set; }
    }
}
