//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApuestasPolla.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Usuario
    {
        public Usuario()
        {
            this.ApuestaPartido = new HashSet<ApuestaPartido>();
        }
        public int IdUsuario { get; set; }

        [Display(Name = "Nombre de Usuario")]
        [StringLength(50)]
        [Required]
        public string Usuario1 { get; set; }

        [Display(Name = "Contraseña")]
        [StringLength(50)]
        [Required]
        [DataType(DataType.Password)]
        public string Contrasena { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Sexo { get; set; }
        public List<SelectListItem> ListaSexos { get; set; } 
        public string Modulo { get; set; }
        public int Cedula { get; set; }

        public virtual ICollection<ApuestaPartido> ApuestaPartido { get; set; }
    }
}
